import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/auth/components/AuthProvider";

export const metadata: Metadata = {
  title: "App new",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`antialiase`}
        >
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
